### ISSUE TITLE
Webpack do not reload page when Twig template is edited

### ISSUE THREAD

**Issue by ryuran** [NightlyCommit/twing-loader#20]
Hello,

When I edit and save my twig file used as template of HtmlWebpackPlugin, I expect to see my browser affected (reload or HMR).

**Comment by ryuran** [comment]
sorry

**Comment by ericmorand** [comment]
Good. Can you explain what happened? Was it a misconfiguration?

**Comment by ryuran** [comment]
Clearly, I don't know. I bet on an human mistake.
- file not save
- looking on an old page of previous dev-server off
- looking on prod instead of dev server

**Comment by ericmorand** [comment]
Ok, good to see that it works. Actually twing-loader only adds a dependency explicitely : the environment module path. All other dependencies (aka the templates coming from include, import...) are required and then resolved by the loader. It should be enough for webpack to consider them as a dependency and watch them. But it's not enough, let me know and I'll have then explicitly declared as dependency.

As said earlier, i'm.quiye new at writing webpack loaders. So don't hesitate if you see things that don't work as expected or could be improved.
