### ISSUE TITLE
twing-loader is not compatible with Twing@4

### ISSUE THREAD

**Issue by ericmorand** [NightlyCommit/twing-loader#21]
Related to https://github.com/NightlyCommit/twing/issues/473

twing-loader is currently not supporting Twing@4 because of async support. Since async support is there to stay, it's time to upgrade twing-loader to a new major version that supports Twing@4.

**Comment by hason** [comment]
@ericmorand Is there a plan to solve this task?

**Comment by ericmorand** [comment]
I fixed the issue in v4.

The major change here is that, Twing rendering being asynchronous, requiring a Twig template using twing-loader returns a Promise:

```ts
const template = require('foo.twig');

template({
    foo: 'bar'
}).then((output) => {
    // do something with the output
});
```
