### ISSUE TITLE
Catch Twing errors and emit them with Webpack API

### ISSUE THREAD

**Issue by titouanmathis** [NightlyCommit/twing-loader#26]
Currrently, errors thrown by Twing are not handled and might break the build. It would be nice to catch these errors and to pass them to the `this.async` function to avoid breaking the build in dev mode.

An example to catch parsing errors: 

```ts
let module: TwingNodeModule;
try {
  module = environment.parse(tokenStream);
} catch (error) {
  callback(error);
  return null;
}
```

**Comment by ericmorand** [comment]
@titouanmathis , can you give `twing-loader@4` a try?

**Comment by titouanmathis** [comment]
Tried it, it seems to be fixed, thanks!
